import React from "react";
import Footer from './components/Footer/Footer'
import HeaderMiddle from './components/Header/HeaderMiddle/HeaderMiddle'
import HeaderTop from './components/Header/HeaderTop/HeaderTop'
import Navbar from './components/Header/NavBar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <HeaderTop />
         <HeaderMiddle />
        <Navbar />
        {children}
        <Footer /></body>
      
    </html>
  )
}
